name: "Get Streamers"
on:
  schedule:
    - cron: "*/10 * * * *"
jobs:
  build-streamers-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Run script
        run: npm run getstreamers
